#!/usr/bin/env bash

usage () {
  echo "Usage: launcher COMMAND CONFIG [--skip-prereqs] [--docker-args STRING]"
  echo "Commands:"
  echo "    start:       Start/initialize the container"
  echo "    stop:        Stop the container"
  echo "    restart:     Restart a container"
  echo "    rebuild:     Rebuild the container"
  echo "    enter:       Open a shell to run commands inside the container"
  echo "    logs:        View the Docker logs for a container"
}

command=$1

if [ -z "$command" ]; then
    usage
    exit 1
fi

run_start() {
        docker-compose up 
}

run_stop() {
        docker-compose down 
}

run_build() {
        docker-compose build --no-cache
}

case "$command" in 
    start)
        run_start
        echo "Container started"
        exit 0
        ;;
    
    stop)
        run_stop
        echo "Container stopped"
        exit 0
        ;;

    restart)
        run_stop
        run_start
        echo "Container restarted"
        exit 0
        ;;

    rebuild)
        run_stop
        run_build
        run_start
        echo "Container rebuilt and restarted"
esac
